#!/usr/bin/env bash
# FiLM PE training script for RIC dataset using PRE-GENERATED shared splits
#
# IMPORTANT: Run scripts/data_util/generate_ric_shared_splits.sh FIRST!
#
# This script uses shared splits to ensure fair comparison across different models

# Parameters (customize via environment overrides when calling this script)
: "${SEED:=2023}"
: "${LM_NAME:=esm2_t33_650M_UR50D}" # protT5_xl_uniref50, esm2_t33_650M_UR50D, esm2_t36_3B_UR50D, esm2_t48_15B_UR50D
: "${EMB:=RIC}"
: "${DATASET:=RIC}"  # Using RIC dataset for comparison
: "${FT_EPOCHS:=30}"
: "${BS:=256}"
: "${LR:=0.0005}"
: "${DEVICES:=0}"
: "${PE_DIM:=512}"

# Map LM_NAME to the short token used in Peng run folders
case "${LM_NAME}" in
  esm1b_t33_650M_UR50S) LM_SHORT="ESM1b_650M" ;;
  esm2_t6_8M_UR50D)    LM_SHORT="ESM2_8M" ;;
  esm2_t12_35M_UR50D)  LM_SHORT="ESM2_35M" ;;
  esm2_t30_150M_UR50D) LM_SHORT="ESM2_150M" ;;
  esm2_t33_650M_UR50D) LM_SHORT="ESM2_650M" ;;
  esm2_t36_3B_UR50D)   LM_SHORT="ESM2_3B" ;;
  esm2_t48_15B_UR50D)  LM_SHORT="ESM2_15B" ;;
  protT5_xl_uniref50)  LM_SHORT="ProtT5_XL" ;;
  *) LM_SHORT="NA" ;;
esac

LR_FMT=$(printf '%.6f' "${LR}")

sbatch --wait << EOF
#!/bin/bash

#SBATCH -J FiLM_PE_RIC_${LM_SHORT}_S${SEED}
#SBATCH --output=$HOME/RBP_IG/scripts/sbatch_logs/FiLM_PE_RIC_${LM_SHORT}_S${SEED}_%j.txt
#SBATCH --error=$HOME/RBP_IG/scripts/sbatch_logs/FiLM_PE_RIC_${LM_SHORT}_S${SEED}_%j.txt
#SBATCH --time=03:00:00
#SBATCH --mem=64G
#SBATCH -c 2
#SBATCH --gres=gpu:1
#SBATCH -p gpu_p
#SBATCH --qos=gpu_normal
##SBATCH --constraint=a100_80gb
#SBATCH --nice=10000

source /path/to/home/.bashrc
source /path/to/miniconda3/bin/activate rbp_ig_lustre
cd /path/to/RBP_IG/

SEED="${SEED}"

# ========================================================================
# NO SPLIT GENERATION - Using pre-generated shared splits!
# ========================================================================
# The splits were generated by: scripts/data_util/generate_ric_shared_splits.sh
# Expected file pattern:
#   data/splits/RIC_human_fine-tuning_film_pe_seed_${SEED}_${LM_NAME}__ft_train.tsv
#   data/splits/RIC_human_fine-tuning_film_pe_seed_${SEED}_${LM_NAME}__ft_val.tsv

echo "========================================"
echo "FiLM PE Training - RIC Dataset"
echo "========================================"
echo "Model: FiLM_PE"
echo "LM: ${LM_NAME} (${LM_SHORT})"
echo "Dataset: ${DATASET}_human_fine-tuning.pkl"
echo "Seed: ${SEED}"
echo "PE Dim: ${PE_DIM}"
echo ""
echo "Using PRE-GENERATED shared splits"
echo "Expected split files:"
echo "  data/splits/RIC_human_fine-tuning_film_pe_seed_${SEED}_${LM_NAME}__ft_train.tsv"
echo "  data/splits/RIC_human_fine-tuning_film_pe_seed_${SEED}_${LM_NAME}__ft_val.tsv"
echo ""

# Verify splits exist
SPLIT_TRAIN="/path/to/RBP_IG_storage/data/splits/RIC_human_fine-tuning_film_pe_seed_${SEED}_${LM_NAME}__ft_train.tsv"
SPLIT_VAL="/path/to/RBP_IG_storage/data/splits/RIC_human_fine-tuning_film_pe_seed_${SEED}_${LM_NAME}__ft_val.tsv"

if [ ! -f "\${SPLIT_TRAIN}" ] || [ ! -f "\${SPLIT_VAL}" ]; then
    echo "ERROR: Split files not found!"
    echo "Please run: scripts/data_util/generate_ric_shared_splits.sh ${SEED}"
    exit 1
fi

echo "✓ Split files found"
echo ""

# Fine-tuning
python3 scripts/training/train.py \
  -M FiLM_PE \
  -D ${DEVICES} \
  -DS ${DATASET}_human_fine-tuning.pkl \
  -lm ${LM_NAME} \
  -ef "${EMB}" \
  -S "${SEED}" \
  -e ${FT_EPOCHS} \
  -bs ${BS} \
  -lr ${LR} \
  --pe_dim ${PE_DIM} \
  --patience 5 \
  --keep_small_val_batches

EOF
