#!/usr/bin/env bash
# LoRA training script for RIC dataset using PRE-GENERATED shared splits
#
# IMPORTANT: Run scripts/data_util/generate_ric_shared_splits.sh FIRST!
#
# This script uses shared splits to ensure fair comparison across different models

# Parameters (customize via environment overrides when calling this script)
: "${SEED:=2023}"
: "${LM_NAME:=esm2_t33_650M_UR50D}"  # esm2_t33_650M_UR50D or protT5_xl_uniref50
: "${EMB:=RIC}"
: "${DATASET:=RIC}"  # Using RIC dataset for comparison
: "${FT_EPOCHS:=20}"
: "${BS:=256}"         # Global batch size
: "${LORA_BS:=2}"      # Per-device batch size (keep low for large models!)
: "${LR:=0.0003}"      # LoRA learning rate (often higher than full FT)
: "${DEVICES:=0}"      # GPU device ID
: "${PE_DIM:=512}"     # Positional Encoding dimension (0 to disable)

# Map LM_NAME to the short token used in run folders
case "${LM_NAME}" in
  esm1b_t33_650M_UR50S) LM_SHORT="ESM1b_650M" ;;
  esm2_t6_8M_UR50D)    LM_SHORT="ESM2_8M" ;;
  esm2_t12_35M_UR50D)  LM_SHORT="ESM2_35M" ;;
  esm2_t30_150M_UR50D) LM_SHORT="ESM2_150M" ;;
  esm2_t33_650M_UR50D) LM_SHORT="ESM2_650M" ;;
  esm2_t36_3B_UR50D)   LM_SHORT="ESM2_3B" ;;
  esm2_t48_15B_UR50D)  LM_SHORT="ESM2_15B" ;;
  protT5_xl_uniref50)  LM_SHORT="ProtT5_XL" ;;
  *) LM_SHORT="NA" ;;
esac

LR_FMT=$(printf '%.6f' "${LR}")

sbatch --wait << EOF
#!/bin/bash

#SBATCH -J LoRA_RIC_${LM_SHORT}_S${SEED}
#SBATCH --output=$HOME/RBP_IG/scripts/sbatch_logs/LoRA_RIC_${LM_SHORT}_S${SEED}_%j.txt
#SBATCH --error=$HOME/RBP_IG/scripts/sbatch_logs/LoRA_RIC_${LM_SHORT}_S${SEED}_%j.txt
#SBATCH --time=24:00:00
#SBATCH --mem=64G
#SBATCH -c 4
#SBATCH --gres=gpu:1
#SBATCH -p gpu_p
#SBATCH --qos=gpu_normal
#SBATCH --constraint=a100_80gb
#SBATCH --nice=10000

# Activate Environment
source /path/to/home/.bashrc
source /path/to/miniconda3/bin/activate rbp_ig_lustre
cd /path/to/RBP_IG/

# ========================================================================
# NO SPLIT GENERATION - Using pre-generated shared splits!
# ========================================================================
# The splits were generated by: scripts/data_util/generate_ric_shared_splits.sh
# Expected file pattern:
#   data/splits/RIC_human_fine-tuning_lora_seed_${SEED}_${LM_NAME}__ft_train.tsv
#   data/splits/RIC_human_fine-tuning_lora_seed_${SEED}_${LM_NAME}__ft_val.tsv

echo "========================================"
echo "LoRA Training - RIC Dataset"
echo "========================================"
echo "Model: Lora"
echo "LM: ${LM_NAME} (${LM_SHORT})"
echo "Dataset: ${DATASET}_human_fine-tuning.pkl"
echo "Seed: ${SEED}"
echo "PE Dim: ${PE_DIM}"
echo ""
echo "Using PRE-GENERATED shared splits"
echo "Expected split files:"
echo "  data/splits/RIC_human_fine-tuning_lora_seed_${SEED}_${LM_NAME}__ft_train.tsv"
echo "  data/splits/RIC_human_fine-tuning_lora_seed_${SEED}_${LM_NAME}__ft_val.tsv"
echo ""

# Verify splits exist
SPLIT_TRAIN="/path/to/RBP_IG_storage/data/splits/RIC_human_fine-tuning_lora_seed_${SEED}_${LM_NAME}__ft_train.tsv"
SPLIT_VAL="/path/to/RBP_IG_storage/data/splits/RIC_human_fine-tuning_lora_seed_${SEED}_${LM_NAME}__ft_val.tsv"

if [ ! -f "\${SPLIT_TRAIN}" ] || [ ! -f "\${SPLIT_VAL}" ]; then
    echo "ERROR: Split files not found!"
    echo "Please run: scripts/data_util/generate_ric_shared_splits.sh ${SEED}"
    exit 1
fi

echo "✓ Split files found"
echo ""

# LoRA Fine-tuning
python3 scripts/training/train.py \
  -M Lora \
  -D ${DEVICES} \
  -DS ${DATASET}_human_fine-tuning.pkl \
  -lm ${LM_NAME} \
  -ef "${EMB}" \
  -S "${SEED}" \
  -bs ${BS} \
  --lora_per_device_bs ${LORA_BS} \
  --lora_learning_rate ${LR} \
  --lora_num_train_epochs ${FT_EPOCHS} \
  --pe_dim ${PE_DIM} \
  --patience 10

EOF
